name: Job Fetcher Workflow

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  fetch-jobs:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository to the GitHub Actions runner
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install the required dependencies and Playwright
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          playwright install

      # Validate that the necessary environment variables are defined
      - name: Validate environment variables
        run: |
          if [ -z "$EMAIL_ADDRESS" ] || [ -z "$EMAIL_USER" ] || [ -z "$EMAIL_PASSWORD" ]; then
            echo "Required environment variables are not set."
            exit 1
          fi

      # Cache the job list between runs
      - name: Cache job list
        id: cache-job-list
        uses: actions/cache@v2
        with:
          path: job_list_cache
          key: job-list-cache

      # Run the Python script to fetch job listings and send email
      - name: Run job fetcher script
        run: |
          source .venv/bin/activate
          python main.py
