name: Scheduled Job Fetcher

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch-jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run job fetcher script
      run: python main.py

    - name: Cache job list
      uses: actions/cache@v2
      with:
        path: job_list_cache
        key: ${{ runner.os }}-job-list
        restore-keys: |
          ${{ runner.os }}-job-list
